name: 'Python bandit security scanning action'
description: | 
  Bandit is a tool designed to find common security issues in Python code. 
  This action runs bandit against a directory of Python code and uploads the results as an artifact
inputs:
  bandit-config:
    description: 'Bandit configuration file'
    required: false
  input-dir:
    description: 'Directory to scan'
    required: false
    default: '.'
  format:
    description: 'Output format (txt, csv, json, xml, yaml). Default: json'
    required: false
    default: 'json'
  output-file:
    description: 'Output file name. Default: bandit-report.json'
    required: false
    default: 'bandit-report.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.format }}
    - ${{ inputs.bandit-config }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-file }}