name: 'Python security scanning action'
description: |
  GitHub Action to run security scan on your Python code using.
branding:
  icon: 'check-square'
  color: 'green'
author: 'Amikos Tech Ltd.'
inputs:
  bandit-config:
    description: 'Bandit configuration file'
    required: false
  input-dir:
    description: 'Directory to scan'
    required: false
    default: '.'
  format:
    description: 'Output format (txt, csv, json, xml, yaml). Default: json'
    required: false
    default: 'json'
  output-file:
    description: 'Output file name. Default: bandit-report.json'
    required: false
    default: 'bandit-report.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.format }}
    - ${{ inputs.bandit-config }}
    - ${{ inputs.input-dir }}
    - ${{ inputs.output-file }}